import React from "react";
import Head from "next/head";

const PageHead = () => {
  return (
    <Head>
      <title>どきゅまね</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageHead;
